# nginx server configuration that sets up a web server for the WordPress site with ssl encryption
server {
    listen 443 ssl http2; # http2 allows for multiple requests over a single connection
    server_name ${DOMAIN_NAME} localhost;
    
    # SSL Configuration
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3; # only allows secure TLS versions
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off; # let's client choose best cipher
    
    root /var/www/html; # where WordPress files are stored
    index index.php index.html; # default files to serve
    
    # $uri - tries to serve the exact file requested
    # $uri/ - if the file doesn't exist, try as a directory
    # /index.php?$args - if none of the above work, redirect to WordPress
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    # handles direct php file requests and when try_files redirects to /index.php?$args
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$; # splits url path infor into scritp name and path info
        fastcgi_pass wordpress:9000; # port where PHP-FPM listens
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    
    # Deny access to hidden files
    location ~ /\. {
        deny all;
    }
}