# main nginx configuration file that sets up the global settings for this webserver
events {
    worker_connections 1024; # each worker can handle 1024 simultaneous connections
}

http {
    include       /etc/nginx/mime.types; # loads file type definitions (CSS, JS, images, etc.)
    default_type  application/octet-stream; # fallback for unknown file types
    
    sendfile        on; # efficient file serving (faster than read/write)
    keepalive_timeout  65; # keep connections alive for 65 seconds
    
    include /etc/nginx/conf.d/*.conf;
}