services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - '443:443' # sole entry point into the infrastructure (only external access point)
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/andreas/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/andreas/data/wordpress
      o: bind

# docker network that establishes the connection between containers
# bridge driver is the default for single-host networks
# custom network let's containers communitcate by name instead of IP addresses (names are always the same, IPs change with restart)
networks:
  inception:
    driver: bridge