#PHP FastCGI Process Manager
# nginx receives http requet -> nginx forwards php request to PHP-FPM on port 9090
# -> PHP-FPM processes the php code (WordPress) -> PHP-FPM returns the result nginx
# -> nginx sends result back to the client
[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
listen.owner = www-data
listen.group = www-data
# process pool management 
pm = dynamic
pm.max_children = 5 # max processes that can run simultaneously
pm.start_servers = 2 # start with 2 servers
pm.min_spare_servers = 1 # always keep at least 1 idle process ready
pm.max_spare_servers = 3 # keep max 2 idle processes ready